### PR TITLE
Translation Korean Finish and fix PHP binary

### PR DESCRIPTION
**Pull request by nnnlog**
Translation Korean Finish
Translation by cws06099@gmail.com.
If you want question, you have to send to cws06099@gmail.com

New PHP version(7.0.10) - This supprort Genisys' XBOX AUTH
This is from https://itxtech.org/downloads/ site

thank you

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
@fengberd @ParkChanSol I also speak Korean, and I don't think I actually need to edit it for better translation. There are few of stuffs that would make it better (on my opinion), but it doesn't matter with meaning of strings.

**Comment by smlrrlms** [comment]
this build of php with zip?

**Comment by nnnlog** [comment]
@samalero I use 7-zip when compress php7.tar.gz
Is it make problem?

**Comment by smlrrlms** [comment]
no no this build have zip extension?

**Comment by nnnlog** [comment]
@samalero maybe

**Comment by TheDiamondYT1** [comment]
You should zip it, and busybox contains an unzip command.

**Pull request merged**
