### PR TITLE
Update to Material Design, switch to NotificationCompat

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
The old method of creating a notification is deprecated. I also updated to Material Design.

**Images:** http://m.imgur.com/a/yi1qK

### CODE REVIEW

**Comment by fengberd** [comment]
I'm sorry for my late reply,but I think materialdesign isn't very good on 4.4.4...
And I updated notification code,so I must close this PR.
Thanks for your understanding.
:P

**Comment by TheDiamondYT1** [comment]
Material design does look good on 4.4, and many apps are updating so holo looks out of place

**Comment by fengberd** [comment]
Oh,but lots of apps also in holo design,and I think they looks good too.

**Comment by TheDiamondYT1** [comment]
Lots of apps are holo because they use Theme.DeviceDefault

**Comment by fengberd** [comment]
Yep,so they looks good on both 4.4 and 5.0+.
I think suitable is the best :P

**Comment by TheDiamondYT1** [comment]
Not really.

**Pull request closed without merging**
