### PR TITLE
Add Traditional Chinese

### PR DESCRIPTION
**Pull request by GoneTone**

### CODE REVIEW

**Comment by Yoyu666** [comment]
这不是！大大吗？ヽ(•ω•ゞ)

**Comment by GoneTone** [comment]
@Yoyu666 你是?

**Comment by Yoyu666** [comment]
某某人XD

**Comment by GoneTone** [comment]
@@?

**Comment by fengberd** [comment]
I'm sorry for merge it too late.
:P

**Comment by GoneTone** [comment]
ok

**Pull request merged**
