### PR TITLE
Happy 2017!

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
This pull request updates copyright date.

### CODE REVIEW

**Review by nnnlog — CHANGES_REQUESTED** [review]
제 생각은 2016을 2017로 바꾸는거 보다
 Copyright 2016-2017 이렇게 바꾸는게 더 나을것 같아여

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 아 맞다, 또 잊고 그냥 2017로 수정했네요. 지적 감사합니다.

**Review by nnnlog — APPROVED** [review]
I think approve

**Comment by Johnmacrocraft** [comment]
@fengberd @ParkChanSol, (And some people that I forgot to mention but part of this comment (?))
P.S: I'm pretty sure about this pull request isn't late for us (I mean, this pull request isn't late to get created with name **Happy new year!** for us), because like you guys know, according to **Lunar calendar** the date I made this pull request is almost new year. Not really important for this pull request, but whatever. (?)

**Comment by nnnlog** [comment]
@Johnmacrocraft Ok. :+1:

**Comment by Johnmacrocraft** [comment]
@fengberd Not related to this pull request, but do I (we) need to keep *ROOT* in *button_mount* (and don't translate)? Nobody translated it to their own language except me (us) (Korean).

**Comment by Johnmacrocraft** [comment]
@fengberd Please respond?

**Comment by nnnlog** [comment]
Project Die? (ㅡ.ㅡ)

**Comment by fengberd** [comment]
Nope,but I'm busy with study



Best Regards,
FENGberd

**Comment by nnnlog** [comment]
@fengberd I hope to achieve your dream. Dreams come true!

**Comment by Johnmacrocraft** [comment]
@fengberd
> _**LOL I FORGOT THAT**_

**Pull request merged**
