### PR TITLE
Update Korean translation and change some small stuffs

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
The biggest translation update!

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
For s**t part, I translated it to match original sentence as possible.

**Review by nnnlog — APPROVED** [review]
gooood

**Comment by fengberd** [comment]
Good update,but the new version may not be published in recent :)
I'm ran out of ideas about new functions lol.

**Comment by Johnmacrocraft** [comment]
@fengberd Oh, ok.
Could you change _**성능을 줄일 수 있습니다.**_ to _**성능이 저하될 수 있습니다.**_ on your next commit? Of course I can create new pull request again, but I think it's not worth to create more than one pull request in a day (spamming).

**Comment by Johnmacrocraft** [comment]
@fengberd Also this: _**동의 &amp; 계속**_ to _**동의 및 계속**_

**Comment by fengberd** [comment]
I'm in school right now,next commit may be put off until 2017.10.1 or even
later...

**Comment by Johnmacrocraft** [comment]
@fengberd Emm... You forgot changing stuffs along with your two commits that I've requested?

**Comment by fengberd** [comment]
Done

**Comment by Johnmacrocraft** [comment]
@fengberd Thank you!

**Pull request merged**
