### PR TITLE
Update PocketMine-MP jenkins

### PR DESCRIPTION
**Pull request by mmhobi7**
They moved to https://github.com/pmmp/PocketMine-MP/ and consequently https://jenkins.pmmp.gq/job/PocketMine-MP/

### CODE REVIEW

**Comment by nnnlog** [comment]
Oh!
Is that a PMMP new page?

**Comment by mmhobi7** [comment]
Yup! Pmmp moved

**Comment by fengberd** [comment]
So should I change the GitHub address on ZXDA jenkins?

**Comment by mmhobi7** [comment]
You should yeah

**Pull request merged**
